### ISSUE TITLE
Need to be able to specify host in the Operate ingress

### ISSUE THREAD

**Issue by PashCracken** [zeebe-io/zeebe-operate-helm#1]
We use an installation where we already have an nginx ingress controller installed. In this shared cluster environment we can't use host * and path / as the ingress for Operate.

We need to be able to specify the host that will be used in the Operate ingress.
Please extend the Helm chart to support this

**Comment by salaboy** [comment]
@PashCracken thanks for reporting this issue. 
You can already override chart values with your own Values.yaml file right? Or when installing overriding the specific host for the ingress. If you are not able to do that can you please elaborate on what kind of support do you need? 

Cheers

**Comment by salaboy** [comment]
@PashCracken sorry for the late reply.. for some reason I am not getting these notifications.. I should get them now

**Comment by salaboy** [comment]
@PashCracken after looking into what you need I think that the best way is for the Zeebe Operate chart to optionally provide the Ingress. So you can provide your own ingress if you want to without the one in operate getting in the middle. Does that approach make sense to you?

**Comment by salaboy** [comment]
@PashCracken I am closing this issue because:
1) You can always deploy Zeebe-cluster & Zeebe-Operate charts without deploying the Ingress Controller
2) You can have your own ingress definition which will be custom to your ingress controller of choice.. 

Hopefully that make sense.. If you have feedback or if you still think that the charts needs to be changed please create a more concrete issue. I will be happy to look into it.
