### ISSUE TITLE
Possibility to change path to operate

### ISSUE THREAD

**Issue by alvarosola1** [zeebe-io/zeebe-operate-helm#11]
I've tried to change path to expose operator through ingress-nginx with path-rewrite but not possible, it search static content in root context

I've tried too to change the spring boot context but keep searching static content in /

Any solution?

**Comment by salaboy** [comment]
@alvarosola1 hi there.. thanks for reporting this, it sounds more like a question.. 
what are you changing and what do you want to achieve? 
In general, instead of changing the "context" which is what comes after the / you add a subdomain to avoid modifying the application relative paths. It did take me a while to realize that, so does it make sense to you?

**Comment by alvarosola1** [comment]
Hi, thank you for your quick response!

I want to expose operate which listen to root path (/) in ingress in nginx with already have thay path used.

For example: https://url/zeebe/operator

That is work great but no for static context which is trying to get it in root path

**Comment by salaboy** [comment]
@alvarosola1 that is not so easy to achieve, I've seen a lot of projects recommending against doing that, instead what you can achieve with Ingress is to have something more like
zeebe-cluster.domain.com
operate.domain.com
that can be achieved with the host property in the ingress.

**Comment by salaboy** [comment]
@alvarosola1 can you give that a try? and let me know if that works, I would like to close this issue, as I know for sure that we will not work to enable that in the near future.

**Comment by ChrisKujawa** [comment]
I feel this is out dated if not feel free to reopen it on the mono repo https://github.com/camunda-community-hub/camunda-cloud-helm
